/**
 * lib/exportReport.js — Export analysis data as Markdown or JSON files.
 *
 * Pure utility functions — no React hooks or 'use client' needed.
 */

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

function downloadFile(content, filename, type = 'text/markdown') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function repoName(repoPath) {
  if (!repoPath) return 'unknown';
  return repoPath.replace(/\\/g, '/').split('/').filter(Boolean).pop() || 'repo';
}

function now() {
  return new Date().toLocaleString();
}

// ---------------------------------------------------------------------------
// Health Report
// ---------------------------------------------------------------------------

/**
 * Export a Markdown health report.
 * @param {object} healthData — from GET /api/health
 * @param {string} repoPath
 */
export function exportHealthReport(healthData, repoPath) {
  if (!healthData) return;

  const name = repoName(repoPath);
  const lines = [
    `# Health Report — ${name}`,
    '',
    `> Generated on ${now()}`,
    '',
    '---',
    '',
    '## Overall Score',
    '',
    `**${healthData.score} / 100**`,
    '',
    `Total modules analyzed: ${healthData.total_modules || 'N/A'}`,
    '',
  ];

  // God Modules
  lines.push('## God Modules', '');
  if (healthData.god_modules?.length > 0) {
    lines.push('| File | In-degree | Severity |');
    lines.push('|------|-----------|----------|');
    healthData.god_modules.forEach((m) => {
      lines.push(`| \`${m.file}\` | ${m.value} | ${m.severity} |`);
    });
  } else {
    lines.push('No god modules detected. ✓');
  }
  lines.push('');

  // Coupled Modules
  lines.push('## Coupled Modules', '');
  if (healthData.coupled_modules?.length > 0) {
    lines.push('| File | Out-degree | Severity |');
    lines.push('|------|------------|----------|');
    healthData.coupled_modules.forEach((m) => {
      lines.push(`| \`${m.file}\` | ${m.value} | ${m.severity} |`);
    });
  } else {
    lines.push('No coupled modules detected. ✓');
  }
  lines.push('');

  // Isolated
  lines.push('## Isolated Modules', '');
  lines.push(`Count: **${healthData.isolated_count ?? 0}**`);
  lines.push('');
  lines.push('---', '', `*Report generated by CNI*`);

  downloadFile(lines.join('\n'), `health-report-${today()}.md`);
}

// ---------------------------------------------------------------------------
// Impact Report
// ---------------------------------------------------------------------------

/**
 * Export a Markdown impact analysis report.
 * @param {object} impactData — from POST /api/impact
 * @param {string} fileName — the analyzed file name
 * @param {string} repoPath
 */
export function exportImpactReport(impactData, fileName, repoPath) {
  if (!impactData) return;

  const name = repoName(repoPath);
  const lines = [
    `# Impact Analysis — ${fileName}`,
    '',
    `> Repository: ${name}`,
    `> Generated on ${now()}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Risk Level | **${impactData.risk}** |`,
    `| Direct Dependents | ${impactData.direct} |`,
    `| Transitive Dependents | ${impactData.transitive} |`,
    '',
  ];

  // Dependents table
  lines.push('## Critical Dependents', '');
  if (impactData.dependents?.length > 0) {
    lines.push('| # | File | Criticality |');
    lines.push('|---|------|-------------|');
    impactData.dependents.forEach((dep, i) => {
      lines.push(`| ${i + 1} | \`${dep.file}\` | ${dep.score.toFixed(1)} |`);
    });
  } else {
    lines.push('No dependents found.');
  }
  lines.push('');
  lines.push('---', '', `*Report generated by CNI*`);

  const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, '_');
  downloadFile(lines.join('\n'), `impact-${safeName}-${today()}.md`);
}

// ---------------------------------------------------------------------------
// Onboarding Report
// ---------------------------------------------------------------------------

/**
 * Export a Markdown onboarding guide.
 * @param {object} onboardData — from GET /api/onboard
 * @param {string} repoPath
 */
export function exportOnboardReport(onboardData, repoPath) {
  if (!onboardData) return;

  const name = repoName(repoPath);
  const lines = [
    `# Onboarding Guide — ${name}`,
    '',
    `> Generated on ${now()}`,
    '',
    '---',
    '',
  ];

  // Entry points
  lines.push('## Entry Points', '');
  if (onboardData.entry_points?.length > 0) {
    onboardData.entry_points.forEach((ep) => {
      const short = ep.split(/[/\\]/).pop();
      lines.push(`- \`${short}\``);
    });
  } else {
    lines.push('No entry points detected.');
  }
  lines.push('');

  // Critical modules
  lines.push('## Critical Modules', '');
  if (onboardData.critical_modules?.length > 0) {
    lines.push('| # | Module | Centrality |');
    lines.push('|---|--------|------------|');
    onboardData.critical_modules.forEach((mod, i) => {
      lines.push(`| ${i + 1} | \`${mod.name}\` | ${mod.centrality.toFixed(3)} |`);
    });
  } else {
    lines.push('No critical modules detected.');
  }
  lines.push('');

  // Dead modules
  if (onboardData.dead_modules?.length > 0) {
    lines.push('## Dead Modules', '');
    onboardData.dead_modules.forEach((dm) => {
      lines.push(`- \`${dm}\``);
    });
    lines.push('');
  }

  // Architecture summary
  if (onboardData.summary) {
    lines.push('## Architecture Summary', '');
    lines.push(onboardData.summary);
    lines.push('');
  }

  lines.push('---', '', `*Report generated by CNI*`);

  downloadFile(lines.join('\n'), `onboarding-guide-${today()}.md`);
}

// ---------------------------------------------------------------------------
// Graph Data (JSON)
// ---------------------------------------------------------------------------

/**
 * Export the graph data as a JSON file.
 * @param {Array} nodes
 * @param {Array} edges
 * @param {string} repoPath
 */
export function exportGraphData(nodes, edges, repoPath) {
  const payload = {
    repo: repoPath || '',
    generated: new Date().toISOString(),
    node_count: nodes.length,
    edge_count: edges.length,
    nodes: nodes.map((n) => ({
      id: n.id,
      label: n.label,
      indegree: n.indegree,
      outdegree: n.outdegree,
    })),
    edges: edges.map((e) => ({
      source: typeof e.source === 'object' ? e.source.id : e.source,
      target: typeof e.target === 'object' ? e.target.id : e.target,
    })),
  };

  downloadFile(
    JSON.stringify(payload, null, 2),
    `graph-data-${today()}.json`,
    'application/json',
  );
}
